# Generated by Django 5.2.8 on 2025-12-01 00:49

import apps.reports.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('police', 'Поліція'), ('utility', 'Комунальне підприємство'), ('mayor', 'Мерія'), ('feedback', "Зворотній зв'язок")], max_length=20, verbose_name='Звернення у')),
                ('police_category', models.CharField(blank=True, choices=[('narcotic', 'Наркозлочин'), ('other', 'Інше правопорушення')], max_length=20, null=True, verbose_name='Категорія (поліція)')),
                ('text', models.TextField(verbose_name='Текст повідомлення')),
                ('location_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локація (текстом)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Довгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Відправлено користувачем')),
            ],
            options={
                'verbose_name': 'Звернення',
                'verbose_name_plural': 'Звернення',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я")),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Населений пункт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Користувач Telegram',
                'verbose_name_plural': 'Користувачі Telegram',
            },
        ),
        migrations.CreateModel(
            name='AppealMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.reports.models.appeal_media_path, verbose_name='Файл')),
                ('telegram_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram file_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='reports.appeal', verbose_name='Звернення')),
            ],
            options={
                'verbose_name': 'Медіа',
                'verbose_name_plural': 'Медіа',
            },
        ),
        migrations.AddField(
            model_name='appeal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='reports.telegramuser', verbose_name='Користувач'),
        ),
    ]
