# Generated by Django 5.2.8 on 2025-12-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Номер телефону'),
        ),
    ]
